baseURL = "/"
languageCode = "de-de"
title = "Kube Beispielseite"
theme = "kube"
description = "Dies ist eine Beispiel-Seite für das Hugo-Theme Kube."
[Params]
  RSSLink = "/index.xml"
  author = "Testuser" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "joerg@joergpeters.net"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
